//! Portable milestone foundation. This is not a production vault format.
pub mod identity;
pub mod vault;
use argon2::{Algorithm, Argon2, Params, Version};
use chacha20poly1305::{
    aead::{Aead, KeyInit, Payload},
    XChaCha20Poly1305, XNonce,
};
use nostr::event::Event;
use serde::{Deserialize, Serialize};
use zeroize::Zeroizing;

pub const MAX_EVENT: usize = 65_536;
pub const MAX_PAYLOAD: usize = 1_048_576;
pub const MAX_BATCH: usize = 16;
pub const VERSION: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    Malformed,
    Unsupported,
    Limit,
    InvalidId,
    InvalidSignature,
    OutOfScope,
    Authentication,
    Crypto,
    CryptoWork,
    Storage,
    Cancelled,
    Busy,
    Randomness,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FoundationError {
    pub code: ErrorCode,
}
impl FoundationError {
    pub fn new(code: ErrorCode) -> Self {
        Self { code }
    }
}
impl std::fmt::Display for FoundationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "foundation {:?}", self.code)
    }
}
impl std::error::Error for FoundationError {}
pub type Result<T> = std::result::Result<T, FoundationError>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct FoundationRequest {
    pub version: u32,
    pub request_id: String,
    pub operation: String,
    pub event_length: usize,
    pub payload_length: usize,
}
impl FoundationRequest {
    pub fn validate(&self, event: &[u8], payload: &[u8]) -> Result<ValidatedEvent> {
        if self.version != VERSION || self.operation != "foundation_proof" {
            return Err(FoundationError::new(ErrorCode::Unsupported));
        }
        if self.request_id.is_empty()
            || self.request_id.len() > 64
            || !self
                .request_id
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
        {
            return Err(FoundationError::new(ErrorCode::Malformed));
        }
        if event.len() > MAX_EVENT || payload.len() > MAX_PAYLOAD {
            return Err(FoundationError::new(ErrorCode::Limit));
        }
        if self.event_length != event.len() || self.payload_length != payload.len() {
            return Err(FoundationError::new(ErrorCode::Malformed));
        }
        validate_event(event)
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidatedEvent {
    pub id: String,
    pub pubkey: String,
}
pub fn validate_event(input: &[u8]) -> Result<ValidatedEvent> {
    if input.len() > MAX_EVENT {
        return Err(FoundationError::new(ErrorCode::Limit));
    }
    let event: Event =
        serde_json::from_slice(input).map_err(|_| FoundationError::new(ErrorCode::Malformed))?;
    if event.tags.len() > 256 || event.content.len() > MAX_EVENT {
        return Err(FoundationError::new(ErrorCode::Limit));
    }
    if !event.verify_id() {
        return Err(FoundationError::new(ErrorCode::InvalidId));
    }
    if !event.verify_signature() {
        return Err(FoundationError::new(ErrorCode::InvalidSignature));
    }
    if event.kind.as_u16() != 1
        || event.pubkey.to_hex()
            != "1b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f"
    {
        return Err(FoundationError::new(ErrorCode::OutOfScope));
    }
    Ok(ValidatedEvent {
        id: event.id.to_hex(),
        pubkey: event.pubkey.to_hex(),
    })
}

/// Entropy must be generated by the host's cryptographically secure RNG.
/// Deliberately has no Debug or serialization implementation.
pub struct RandomMaterial {
    pub salt: [u8; 16],
    pub data_key: [u8; 32],
    pub wrap_nonce: [u8; 24],
    pub record_nonce: [u8; 24],
}
impl Drop for RandomMaterial {
    fn drop(&mut self) {
        use zeroize::Zeroize;
        self.data_key.zeroize();
    }
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ProtectedRecord {
    pub version: u32,
    pub salt: [u8; 16],
    pub wrap_nonce: [u8; 24],
    pub record_nonce: [u8; 24],
    pub wrapped_key: Vec<u8>,
    pub ciphertext: Vec<u8>,
}
fn aad(context: &str, account: &str, record: &str) -> Result<Vec<u8>> {
    if account.is_empty() || record.is_empty() || account.len() > 128 || record.len() > 128 {
        return Err(FoundationError::new(ErrorCode::Limit));
    }
    serde_json::to_vec(&(VERSION, context, account, record))
        .map_err(|_| FoundationError::new(ErrorCode::Crypto))
}
/// Non-production proof parameters: Argon2id v19, 8 MiB, t=1, p=1.
pub fn derive_key(password: &[u8], salt: &[u8; 16]) -> Result<Zeroizing<[u8; 32]>> {
    if password.is_empty() || password.len() > 1024 {
        return Err(FoundationError::new(ErrorCode::Limit));
    }
    let params =
        Params::new(8192, 1, 1, Some(32)).map_err(|_| FoundationError::new(ErrorCode::Crypto))?;
    let mut key = Zeroizing::new([0; 32]);
    Argon2::new(Algorithm::Argon2id, Version::V0x13, params)
        .hash_password_into(password, salt, &mut *key)
        .map_err(|_| FoundationError::new(ErrorCode::Crypto))?;
    Ok(key)
}
pub fn protect_record(
    password: &[u8],
    payload: &[u8],
    account: &str,
    record: &str,
    random: &RandomMaterial,
) -> Result<ProtectedRecord> {
    if payload.len() > MAX_PAYLOAD {
        return Err(FoundationError::new(ErrorCode::Limit));
    }
    let wrap_aad = aad("wrap", account, record)?;
    let record_aad = aad("record", account, record)?;
    let wrapping = derive_key(password, &random.salt)?;
    let wrapped_key = XChaCha20Poly1305::new((&*wrapping).into())
        .encrypt(
            &XNonce::from(random.wrap_nonce),
            Payload {
                msg: &random.data_key,
                aad: &wrap_aad,
            },
        )
        .map_err(|_| FoundationError::new(ErrorCode::Crypto))?;
    let ciphertext = XChaCha20Poly1305::new((&random.data_key).into())
        .encrypt(
            &XNonce::from(random.record_nonce),
            Payload {
                msg: payload,
                aad: &record_aad,
            },
        )
        .map_err(|_| FoundationError::new(ErrorCode::Crypto))?;
    Ok(ProtectedRecord {
        version: VERSION,
        salt: random.salt,
        wrap_nonce: random.wrap_nonce,
        record_nonce: random.record_nonce,
        wrapped_key,
        ciphertext,
    })
}
pub fn open_record(
    password: &[u8],
    protected: &ProtectedRecord,
    account: &str,
    record: &str,
) -> Result<Zeroizing<Vec<u8>>> {
    if protected.version != VERSION {
        return Err(FoundationError::new(ErrorCode::Unsupported));
    }
    if protected.wrapped_key.len() != 48
        || protected.ciphertext.len() < 16
        || protected.ciphertext.len() > MAX_PAYLOAD + 16
    {
        return Err(FoundationError::new(ErrorCode::Limit));
    }
    let wrap_aad = aad("wrap", account, record)?;
    let record_aad = aad("record", account, record)?;
    let wrapping = derive_key(password, &protected.salt)?;
    let key = Zeroizing::new(
        XChaCha20Poly1305::new((&*wrapping).into())
            .decrypt(
                &XNonce::from(protected.wrap_nonce),
                Payload {
                    msg: &protected.wrapped_key,
                    aad: &wrap_aad,
                },
            )
            .map_err(|_| FoundationError::new(ErrorCode::Authentication))?,
    );
    let cipher = XChaCha20Poly1305::new_from_slice(&key)
        .map_err(|_| FoundationError::new(ErrorCode::Authentication))?;
    cipher
        .decrypt(
            &XNonce::from(protected.record_nonce),
            Payload {
                msg: &protected.ciphertext,
                aad: &record_aad,
            },
        )
        .map(Zeroizing::new)
        .map_err(|_| FoundationError::new(ErrorCode::Authentication))
}

pub const EVENT_JSON: &[u8] = include_bytes!("../fixtures/event.json");
pub const ZIP_BYTES: &[u8] = include_bytes!("../fixtures/payload.zip");
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FoundationResult {
    pub event_id: String,
    pub payload_bytes: usize,
    pub storage_reopened: bool,
    pub crypto_verified: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FoundationResponse {
    pub version: u32,
    pub request_id: String,
    pub result: Option<FoundationResult>,
    pub error: Option<FoundationError>,
}

/// Shared adversarial fixture vectors run inside each actual platform runtime.
/// Uses public test-only data and returns no sensitive diagnostics.
pub fn run_core_proof() -> Result<()> {
    let expected = validate_event(EVENT_JSON)?;
    let mut base: serde_json::Value = serde_json::from_slice(EVENT_JSON)
        .map_err(|_| FoundationError::new(ErrorCode::Malformed))?;
    for (field, value, code) in [
        (
            "content",
            serde_json::json!("changed"),
            ErrorCode::InvalidId,
        ),
        (
            "created_at",
            serde_json::json!(1700000001),
            ErrorCode::InvalidId,
        ),
        (
            "tags",
            serde_json::json!([["changed"]]),
            ErrorCode::InvalidId,
        ),
        (
            "id",
            serde_json::json!("00".repeat(32)),
            ErrorCode::InvalidId,
        ),
        (
            "sig",
            serde_json::json!("00".repeat(64)),
            ErrorCode::InvalidSignature,
        ),
        ("pubkey", serde_json::json!("not hex"), ErrorCode::Malformed),
    ] {
        let original = base[field].clone();
        base[field] = value;
        let bytes =
            serde_json::to_vec(&base).map_err(|_| FoundationError::new(ErrorCode::Malformed))?;
        if validate_event(&bytes).err().map(|e| e.code) != Some(code) {
            return Err(FoundationError::new(ErrorCode::Crypto));
        }
        base[field] = original;
    }
    for (bytes, code) in [
        (b"{".to_vec(), ErrorCode::Malformed),
        (vec![0; MAX_EVENT + 1], ErrorCode::Limit),
        (
            include_bytes!("../fixtures/out-of-scope.json").to_vec(),
            ErrorCode::OutOfScope,
        ),
    ] {
        if validate_event(&bytes).err().map(|e| e.code) != Some(code) {
            return Err(FoundationError::new(ErrorCode::Crypto));
        }
    }
    let key = derive_key(b"foundation password", &[1; 16])?;
    let known = [
        0xea, 0xf5, 0xc0, 0xec, 0xb5, 0x02, 0xe7, 0x31, 0x36, 0x52, 0x4e, 0xc0, 0x17, 0x62, 0x30,
        0xe8, 0x88, 0x21, 0x87, 0x3f, 0xad, 0xbf, 0xde, 0x2d, 0x16, 0x56, 0x72, 0x14, 0xc9, 0xc8,
        0x9a, 0x72,
    ];
    if *key != known {
        return Err(FoundationError::new(ErrorCode::Crypto));
    }
    let random = RandomMaterial {
        salt: [1; 16],
        data_key: [2; 32],
        wrap_nonce: [3; 24],
        record_nonce: [4; 24],
    };
    let encrypted = protect_record(
        b"foundation password",
        ZIP_BYTES,
        &expected.pubkey,
        "fixture",
        &random,
    )?;
    if *open_record(
        b"foundation password",
        &encrypted,
        &expected.pubkey,
        "fixture",
    )? != ZIP_BYTES
    {
        return Err(FoundationError::new(ErrorCode::Crypto));
    }
    let other_random = RandomMaterial {
        salt: [1; 16],
        data_key: [9; 32],
        wrap_nonce: [3; 24],
        record_nonce: [4; 24],
    };
    let mut wrong_key = encrypted.clone();
    wrong_key.wrapped_key = protect_record(
        b"foundation password",
        ZIP_BYTES,
        &expected.pubkey,
        "fixture",
        &other_random,
    )?
    .wrapped_key;
    if open_record(
        b"foundation password",
        &wrong_key,
        &expected.pubkey,
        "fixture",
    )
    .is_ok()
    {
        return Err(FoundationError::new(ErrorCode::Crypto));
    }
    for mutation in 0..7 {
        let mut changed = encrypted.clone();
        match mutation {
            0 => changed.ciphertext[0] ^= 1,
            1 => changed.wrapped_key[0] ^= 1,
            2 => changed.record_nonce[0] ^= 1,
            3 => changed.wrap_nonce[0] ^= 1,
            4 => changed.salt[0] ^= 1,
            5 => {
                changed.ciphertext.pop();
            }
            _ => changed.version += 1,
        }
        if open_record(
            b"foundation password",
            &changed,
            &expected.pubkey,
            "fixture",
        )
        .is_ok()
        {
            return Err(FoundationError::new(ErrorCode::Crypto));
        }
    }
    for (password, account, record) in [
        (b"wrong".as_slice(), expected.pubkey.as_str(), "fixture"),
        (b"foundation password".as_slice(), "wrong", "fixture"),
        (
            b"foundation password".as_slice(),
            expected.pubkey.as_str(),
            "wrong",
        ),
    ] {
        if open_record(password, &encrypted, account, record).is_ok() {
            return Err(FoundationError::new(ErrorCode::Crypto));
        }
    }
    Ok(())
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn shared_core_vectors() {
        run_core_proof().unwrap();
    }
    #[test]
    fn rejects_contract_mutations_before_work() {
        let base = serde_json::json!({"version":1,"requestId":"test-1","operation":"foundation_proof","eventLength":EVENT_JSON.len(),"payloadLength":ZIP_BYTES.len()});
        for (field, value) in [
            ("version", serde_json::json!(2)),
            ("operation", serde_json::json!("unknown")),
            ("requestId", serde_json::json!("")),
            ("eventLength", serde_json::json!(0)),
            ("payloadLength", serde_json::json!(0)),
            ("version", serde_json::json!("1")),
        ] {
            let mut changed = base.clone();
            changed[field] = value;
            let result = serde_json::from_value::<FoundationRequest>(changed)
                .ok()
                .and_then(|r| r.validate(EVENT_JSON, ZIP_BYTES).ok());
            assert!(result.is_none(), "{field}");
        }
        let mut missing = base.clone();
        missing.as_object_mut().unwrap().remove("version");
        assert!(serde_json::from_value::<FoundationRequest>(missing).is_err());
        let valid: FoundationRequest = serde_json::from_value(base).unwrap();
        assert!(valid.validate(EVENT_JSON, ZIP_BYTES).is_ok());
        assert_eq!(
            valid
                .validate(EVENT_JSON, &vec![0; MAX_PAYLOAD + 1])
                .unwrap_err()
                .code,
            ErrorCode::Limit
        );
    }
}
